defmodule PhotoFinish.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :storage_directory, :text
    end
  end

  def down do
    alter table(:events) do
      remove :storage_directory
    end
  end
end
