defmodule PhotoFinish.Repo.Migrations.SetupEventsAndPhotos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :ingestion_path, :text, null: false
      add :current_path, :text
      add :preview_path, :text
      add :thumbnail_path, :text
      add :filename, :text, null: false
      add :original_filename, :text
      add :file_size_bytes, :bigint
      add :mime_type, :text, default: "image/jpeg"
      add :width, :bigint
      add :height, :bigint
      add :photographer, :text
      add :source_folder, :text
      add :captured_at, :utc_datetime
      add :processed_at, :utc_datetime
      add :finalized_at, :utc_datetime
      add :status, :text, default: "discovered"
      add :error_message, :text
      add :exif_data, :map
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :uuid
      add :node_id, :uuid
      add :competitor_id, :uuid
    end

    create table(:hierarchy_nodes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :level_number, :bigint, null: false
      add :name, :text, null: false
      add :slug, :text, null: false
      add :display_order, :bigint, default: 0
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :uuid
      add :parent_id, :uuid
    end

    create table(:hierarchy_levels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :level_number, :bigint, null: false
      add :level_name, :text, null: false
      add :level_name_plural, :text
      add :is_required, :boolean, default: true
      add :allow_photos, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :uuid
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:photos) do
      modify :event_id,
             references(:events,
               column: :id,
               name: "photos_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :node_id,
             references(:hierarchy_nodes,
               column: :id,
               name: "photos_node_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:hierarchy_nodes) do
      modify :event_id,
             references(:events,
               column: :id,
               name: "hierarchy_nodes_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_id,
             references(:hierarchy_nodes,
               column: :id,
               name: "hierarchy_nodes_parent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:hierarchy_levels) do
      modify :event_id,
             references(:events,
               column: :id,
               name: "hierarchy_levels_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:events) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :starts_at, :utc_datetime
      add :ends_at, :utc_datetime
      add :status, :text, default: "active"
      add :order_code, :text
      add :tax_rate_basis_points, :bigint, default: 850

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:competitors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:photos) do
      modify :competitor_id,
             references(:competitors,
               column: :id,
               name: "photos_competitor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:competitors) do
      add :competitor_number, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text
      add :display_name, :text
      add :team_name, :text
      add :level, :text
      add :age_group, :text
      add :email, :text
      add :phone, :text
      add :is_active, :boolean, default: true
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:events,
            column: :id,
            name: "competitors_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :node_id,
          references(:hierarchy_nodes,
            column: :id,
            name: "competitors_node_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop constraint(:competitors, "competitors_event_id_fkey")

    drop constraint(:competitors, "competitors_node_id_fkey")

    alter table(:competitors) do
      remove :node_id
      remove :event_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :is_active
      remove :phone
      remove :email
      remove :age_group
      remove :level
      remove :team_name
      remove :display_name
      remove :last_name
      remove :first_name
      remove :competitor_number
    end

    drop constraint(:photos, "photos_competitor_id_fkey")

    alter table(:photos) do
      modify :competitor_id, :uuid
    end

    drop table(:competitors)

    alter table(:events) do
      remove :updated_at
      remove :inserted_at
      remove :tax_rate_basis_points
      remove :order_code
      remove :status
      remove :ends_at
      remove :starts_at
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:hierarchy_levels, "hierarchy_levels_event_id_fkey")

    alter table(:hierarchy_levels) do
      modify :event_id, :uuid
    end

    drop constraint(:hierarchy_nodes, "hierarchy_nodes_event_id_fkey")

    drop constraint(:hierarchy_nodes, "hierarchy_nodes_parent_id_fkey")

    alter table(:hierarchy_nodes) do
      modify :parent_id, :uuid
      modify :event_id, :uuid
    end

    drop constraint(:photos, "photos_event_id_fkey")

    drop constraint(:photos, "photos_node_id_fkey")

    alter table(:photos) do
      modify :node_id, :uuid
      modify :event_id, :uuid
    end

    drop table(:events)

    drop table(:hierarchy_levels)

    drop table(:hierarchy_nodes)

    drop table(:photos)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
