defmodule PhotoFinish.Repo.Migrations.AddNextOrderNumberToEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :next_order_number, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:events) do
      remove :next_order_number
    end
  end
end
