defmodule PhotoFinish.Repo.Migrations.AddOrdersResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:product_templates, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :product_type, :text, null: false
      add :product_name, :text, null: false
      add :product_size, :text
      add :default_price_cents, :bigint, null: false
      add :is_active, :boolean, default: true
      add :display_order, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:orders, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :order_number, :text, null: false
      add :customer_name, :text, null: false
      add :customer_email, :text
      add :customer_phone, :text
      add :subtotal_cents, :bigint, null: false
      add :tax_rate_basis_points, :bigint, null: false
      add :tax_cents, :bigint, null: false
      add :total_cents, :bigint, null: false
      add :payment_status, :text, default: "pending"
      add :payment_reference, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:events,
            column: :id,
            name: "orders_event_id_fkey",
            type: :text,
            prefix: "public"
          )
    end

    create unique_index(:orders, [:order_number], name: "orders_unique_order_number_index")

    create table(:order_items, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :quantity, :bigint, default: 1
      add :unit_price_cents, :bigint, null: false
      add :line_total_cents, :bigint, null: false
      add :fulfillment_status, :text, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_items_order_id_fkey",
            type: :text,
            prefix: "public"
          )

      add :event_product_id, :text
      add :event_competitor_id, :text
    end

    create table(:event_products, primary_key: false) do
      add :id, :text, null: false, primary_key: true
    end

    alter table(:order_items) do
      modify :event_product_id,
             references(:event_products,
               column: :id,
               name: "order_items_event_product_id_fkey",
               type: :text,
               prefix: "public"
             )

      modify :event_competitor_id,
             references(:event_competitors,
               column: :id,
               name: "order_items_event_competitor_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:event_products) do
      add :price_cents, :bigint, null: false
      add :is_available, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id,
          references(:events,
            column: :id,
            name: "event_products_event_id_fkey",
            type: :text,
            prefix: "public"
          )

      add :product_template_id,
          references(:product_templates,
            column: :id,
            name: "event_products_product_template_id_fkey",
            type: :text,
            prefix: "public"
          )
    end

    create unique_index(:event_products, [:event_id, :product_template_id],
             name: "event_products_unique_event_product_index"
           )
  end

  def down do
    drop_if_exists unique_index(:event_products, [:event_id, :product_template_id],
                     name: "event_products_unique_event_product_index"
                   )

    drop constraint(:event_products, "event_products_event_id_fkey")

    drop constraint(:event_products, "event_products_product_template_id_fkey")

    alter table(:event_products) do
      remove :product_template_id
      remove :event_id
      remove :updated_at
      remove :inserted_at
      remove :is_available
      remove :price_cents
    end

    drop constraint(:order_items, "order_items_event_product_id_fkey")

    drop constraint(:order_items, "order_items_event_competitor_id_fkey")

    alter table(:order_items) do
      modify :event_competitor_id, :text
      modify :event_product_id, :text
    end

    drop table(:event_products)

    drop constraint(:order_items, "order_items_order_id_fkey")

    drop table(:order_items)

    drop_if_exists unique_index(:orders, [:order_number],
                     name: "orders_unique_order_number_index"
                   )

    drop constraint(:orders, "orders_event_id_fkey")

    drop table(:orders)

    drop table(:product_templates)
  end
end
