defmodule PhotoFinish.Repo.Migrations.RefactorEventCompetitors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "CREATE EXTENSION IF NOT EXISTS citext"

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:photos, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :ingestion_path, :text, null: false
      add :current_path, :text
      add :preview_path, :text
      add :thumbnail_path, :text
      add :filename, :text, null: false
      add :original_filename, :text
      add :file_size_bytes, :bigint
      add :mime_type, :text, default: "image/jpeg"
      add :width, :bigint
      add :height, :bigint
      add :photographer, :text
      add :source_folder, :text
      add :captured_at, :utc_datetime
      add :processed_at, :utc_datetime
      add :finalized_at, :utc_datetime
      add :status, :text, default: "discovered"
      add :error_message, :text
      add :exif_data, :map
      add :metadata, :map
      add :gym, :text
      add :session, :text
      add :group_name, :text
      add :apparatus, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :event_id, :text
      add :event_competitor_id, :text
    end

    create table(:events, primary_key: false) do
      add :id, :text, null: false, primary_key: true
    end

    alter table(:photos) do
      modify :event_id,
             references(:events,
               column: :id,
               name: "photos_event_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:events) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :starts_at, :utc_datetime
      add :ends_at, :utc_datetime
      add :status, :text, default: "active"
      add :order_code, :text
      add :tax_rate_basis_points, :bigint, default: 850
      add :storage_root, :text, null: false
      add :num_gyms, :bigint, null: false, default: 1
      add :sessions_per_gym, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:event_competitors, primary_key: false) do
      add :id, :text, null: false, primary_key: true
    end

    alter table(:photos) do
      modify :event_competitor_id,
             references(:event_competitors,
               column: :id,
               name: "photos_event_competitor_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:event_competitors) do
      add :session, :text
      add :competitor_number, :text, null: false
      add :display_name, :text
      add :team_name, :text
      add :level, :text
      add :age_group, :text
      add :is_active, :boolean, default: true
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :competitor_id, :text
      add :event_id, :text
    end

    create table(:competitors, primary_key: false) do
      add :id, :text, null: false, primary_key: true
    end

    alter table(:event_competitors) do
      modify :competitor_id,
             references(:competitors,
               column: :id,
               name: "event_competitors_competitor_id_fkey",
               type: :text,
               prefix: "public"
             )

      modify :event_id,
             references(:events,
               column: :id,
               name: "event_competitors_event_id_fkey",
               type: :text,
               prefix: "public"
             )
    end

    create unique_index(:event_competitors, [:event_id, :competitor_number],
             name: "event_competitors_unique_event_competitor_number_index"
           )

    alter table(:competitors) do
      add :first_name, :text, null: false
      add :last_name, :text
      add :external_id, :text
      add :email, :text
      add :phone, :text
      add :metadata, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    alter table(:competitors) do
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :phone
      remove :email
      remove :external_id
      remove :last_name
      remove :first_name
    end

    drop_if_exists unique_index(:event_competitors, [:event_id, :competitor_number],
                     name: "event_competitors_unique_event_competitor_number_index"
                   )

    drop constraint(:event_competitors, "event_competitors_competitor_id_fkey")

    drop constraint(:event_competitors, "event_competitors_event_id_fkey")

    alter table(:event_competitors) do
      modify :event_id, :text
      modify :competitor_id, :text
    end

    drop table(:competitors)

    alter table(:event_competitors) do
      remove :event_id
      remove :competitor_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :is_active
      remove :age_group
      remove :level
      remove :team_name
      remove :display_name
      remove :competitor_number
      remove :session
    end

    drop constraint(:photos, "photos_event_competitor_id_fkey")

    alter table(:photos) do
      modify :event_competitor_id, :text
    end

    drop table(:event_competitors)

    alter table(:events) do
      remove :updated_at
      remove :inserted_at
      remove :sessions_per_gym
      remove :num_gyms
      remove :storage_root
      remove :tax_rate_basis_points
      remove :order_code
      remove :status
      remove :ends_at
      remove :starts_at
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:photos, "photos_event_id_fkey")

    alter table(:photos) do
      modify :event_id, :text
    end

    drop table(:events)

    drop table(:photos)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
